### ISSUE TITLE
弹出报错信息，运行不了，Cannot find module 'winston'

### ISSUE THREAD

**Issue by sangko-dgq** [HeiSir2014/owt-client-rtc#2]
Error
X
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'winston'
Require stack:
- C:\Users\Administrator\Desktop\owt-client\owt-client-rtc\main.js
C:\Users\Administrator\AppData\Roaming\npm\node_ modulesl\electrond.i..\main.js
at Module. resolveFilename (internal/modules/cjs/loader.js:887:15)
at Function.n. resolveFilename (electron/js2c/browser_ init.js:257:1128)
at Module. load (internal/modules/cjs/loader.js:732:27)
at Function.f._ load (electron/js2c/asar_ bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object. <anonymous>
(C:\Users\Administrator\Desktop\owt-client\owt-client-rtc\main.js:4:17)
at Module._ compile (internal/modules/cjs/loader.js:1078:30)
at Object.Module. extensions..js (internal/modules/cjs/loader.js:1 108:10)
at Module.load (internal/modules/cjs/loader.js:935:32)
确定
...............

**Comment by sangko-dgq** [comment]
> Error
> X
> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Cannot find module 'winston'
> Require stack:
> 
> * C:\Users\Administrator\Desktop\owt-client\owt-client-rtc\main.js
>   C:\Users\Administrator\AppData\Roaming\npm\node_ modulesl\electrond.i..\main.js
>   at Module. resolveFilename (internal/modules/cjs/loader.js:887:15)
>   at Function.n. resolveFilename (electron/js2c/browser_ init.js:257:1128)
>   at Module. load (internal/modules/cjs/loader.js:732:27)
>   at Function.f._ load (electron/js2c/asar_ bundle.js:5:12913)
>   at Module.require (internal/modules/cjs/loader.js:959:19)
>   at require (internal/modules/cjs/helpers.js:88:18)
>   at Object. 
>   (C:\Users\Administrator\Desktop\owt-client\owt-client-rtc\main.js:4:17)
>   at Module._ compile (internal/modules/cjs/loader.js:1078:30)
>   at Object.Module. extensions..js (internal/modules/cjs/loader.js:1 108:10)
>   at Module.load (internal/modules/cjs/loader.js:935:32)
>   确定
>   ...............

**Comment by sangko-dgq** [comment]
解决了，重新yarn一遍模块就可以了
